version: '3.8'

services:
  # Serviço do MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb-extratos
    restart: always
    ports:
      - "27017:27017"
    environment:
      # Configurações de autenticação
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: extratos_portuarios
    volumes:
      # Volume para persistência de dados
      - mongodb_data:/data/db
      # Script de inicialização para criar usuário da aplicação
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  # Interface de administração do MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - app-network

  # Aplicação Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extrator-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://app_user:app_password@mongodb:27017/extratos_portuarios
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
